{
  #"data_path": "/mnt/data/Tejas/GPT-NEOX/custom/BIN/data_text_document",
   "train_data_paths": ["train_test_validate_for_neox/neox_train/neox_train_text_document"],
   "valid_data_paths": ["train_test_validate_for_neox/neox_val/neox_val_text_document"],
   "test_data_paths": ["train_test_validate_for_neox/neox_test/neox_test_text_document"],

  "vocab_file": "train_test_validate_for_neox/slimpajama_val_test_trained_bpe_tok.json",
  "tokenizer_type": "HFTokenizer",

  "checkpoint_validation_with_forward_pass": False,


  "save": "checkpoints/31M_prenorm_layernorm_slimpajama1B",
  "load": "checkpoints/31M_prenorm_layernorm_slimpajama1B",
  "tensorboard_dir": "tensorboard/31M_prenorm_layernorm_slimpajama1B",
  "log_dir": "logs/31M_prenorm_layernorm_slimpajama1B",  

    
   

  #mods
  # "dual_residual": True,
  # # "precision": "bfloat16",
  # "activation": "swiglu",
  # "num_kv_heads": 4,
  # "norm": "crmsnorm",
  #  "crms_norm_epsilon": 1.0e_8,
  

  "use_wandb": False,

  # parallelism settings

   "pipe_parallel_size": 1,
   "model_parallel_size": 1,
  #  "num_gpus": 4,

  
  # model settings
  "num_layers": 6,
  "hidden_size": 256,
  "num_attention_heads": 8,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
 #"num_kv_heads": 8,
   "pos_emb": "learned",
   "no_weight_tying": true,
   #"gpt_j_residual": true,
   "output_layer_parallelism": "column",

   "attention_config": [[["flash"], 6]],

     #  "norm": "rmsnorm",
  #  "rms_norm_epsilon": 1.0e-8,
   "norm": "layernorm",
   #"crms_norm_epsilon": 1.0e-8,
  #  "linear_zero_mean": True,

  #  "norm": "layernorm",
   "norm_rearrange": False, 
   "activation": "swiglu",

   # these should provide some speedup but takes a while to build, set to true if desired
   #"scaled_upper_triang_masked_softmax_fusion": true,
  # "bias_gelu_fusion": true,
  # "rope_fusion": false,
  # "layernorm_fusion": false,

   # init methods
   #"init_method": "small_init",
   #"output_layer_init_method": "wang_init",

   # optimizer settings
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.001,
       "betas": [0.9, 0.95],
       "eps":  1.0e-8,
     }
   },
   "min_lr": 0.0001,
   #"use_checkpoint_lr_scheduler"  : True,

  #  # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 2,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": False,
    
  },

  # batch size (trained on 32 gpus)
  "train_micro_batch_size_per_gpu": 8,
  
  "data-impl": "mmap",
  "num_workers": 1,
  
   #"split": "949,50,1",

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

  # regularization
  #"gradient_clipping": 0.0,
  "weight-decay": 0.1,
  "hidden-dropout": 0,
  "attention-dropout": 0,
  
   # precision settings
  

   "precision": "bfloat16",

   #"fp32_allreduce": True, # without a patch to torch, bf16 models have to do the allreduce in fp32

   # misc. training settings
   "train_iters": 100000,
   "lr_decay_iters": 100000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.00,
   "checkpoint_factor": 5000,
   "eval_interval": 5000,
   "eval_iters": 10,
   "do_test": true,
   "extra_save_iters": [10,100,500,1000],

   # logging
   "log_interval": 100,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 10,
   "wall_clock_breakdown": true,
}