# GPT-2 pretraining setup
{
  # "data_path": "/data/train_text_document",
  "train_data_paths": ["/data/train_text_document"],
  "valid_data_paths": ["/data/validation_text_document"],
  "test_data_paths": ["/data/test_text_document"],

  "vocab_file": "download_slimpajama/tokenizer_loubnabnl_slimpajama.json",
  "tokenizer_type": "HFTokenizer",

  "save": "checkpoints/prenorm-harshit-crms-3B(MOE_8)/",
  "load": "checkpoints/prenorm-harshit-crms-3B(MOE_8)/",

  "checkpoint_validation_with_forward_pass": False,

  "tensorboard_dir": "tensorboard/prenorm-harshit-crms-3B(MOE_8)/",
  "log_dir": "logs/prenorm-harshit-crms-3B(MOE_8)/",

  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox-3B-slimpajama_chunk1",

   "moe_num_experts": 8,
   "moe_expert_parallel_size": 1,
   "moe_top_k": 1,
   # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
   # across the node boundaries )
   "pipe_parallel_size": 1,
   "model_parallel_size": 1,


   "pipe_parallel_size": 1,
   "model_parallel_size": 1,


  # model settings
   "num_layers": 24,
   "hidden_size": 2048,
   "num_attention_heads": 40,
   "num_kv_heads": 8,
   "seq_length": 2048,
   "max_position_embeddings": 2048,
   "pos_emb": "rotary",
   "no_weight_tying": true,
   "gpt_j_residual": false,
   "output_layer_parallelism": "column",

   "attention_config": [[["flash"], 24]],

     #  "norm": "rmsnorm",
  #  "rms_norm_epsilon": 1.0e-8,
  #  "norm": "crmsnorm",
  "norm": "layernorm",
  #  "crms_norm_epsilon": 1.0e-8,
  # #  "norm_rearrange": True, 
  #  "activation": "swiglu",
  #  "linear_zero_mean": True,

   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled_upper_triang_masked_softmax_fusion": false,
   "bias_gelu_fusion": false,
   "rope_fusion": false,
   "layernorm_fusion": false,

   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",

   # optimizer settings
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0002,
       "betas": [0.9, 0.95],
       "eps":  1.0e-8,
     }
   },
   "min_lr": 0.00002,

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": True,
    "allgather_bucket_size": 500000000,
    "overlap_comm": True,
    "reduce_scatter": True,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": True,
  },

   # batch / data settings
   "train_micro_batch_size_per_gpu": 4,
   "data_impl": "mmap",
  #  "split": "949,50,1",

   # activation checkpointing
   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,

  #  #precision settings
   "fp16": {
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   # misc. training settings
   "train_iters": 320000,
   "lr_decay_iters": 320000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 10000,
   "eval_interval": 100,
   "eval_iters": 10,
   "do_test": true,
   "extra_save_iters": [10,100,1000],

   # logging
   "log_interval": 100,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 5,
   "wall_clock_breakdown": true,
}
